
default: &default
   adapter: postgresql
   encoding: unicode
   username: postgres
   password: kamehameha
   hostname: 127.0.0.1
   pool: 5


development:
   <<: *default
   database: kater_development

test:

# As with config/secrets.yml, you never want to store sensitive information,
# like your database password, in your source code. If your source code is
# ever seen by anyone, they now have access to your database.
#
# Instead, provide the password as a unix environment variable when you boot
# the app. Read http://guides.rubyonrails.org/configuring.html#configuring-a-database
# for a full rundown on how to provide these environment variables in a
# production deployment.
#
# On Heroku and other platform providers, you may have a full connection URL
# available as an environment variable. For example:
#
#   DATABASE_URL="postgres://myuser:mypass@localhost/somedatabase"
#
# You can use this database configuration with:
#
#   production:
#     url: <%= ENV['DATABASE_URL'] %>
#
production:
  adapter: postgresql
  encoding: unicode
  username: pyxbzksuvpvune
  password: YoF8FVaQqUS-tkyaKiaRxhM0Wy
  hostname: ec2-54-83-36-176.compute-1.amazonaws.com
  pool: 5
  port: 5432
  url: postgres://pyxbzksuvpvune:YoF8FVaQqUS-tkyaKiaRxhM0Wy@ec2-54-83-36-176.compute-1.amazonaws.com:5432/d6viq40kk3dvm3
  database: d6viq40kk3dvm3